final_pjt/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

final_pjt/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

final_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rank_save/', views.rank_save, name='rank_save'),
    path('<int:movie_pk>/rank_delete/', views.rank_delete, name='rank_delete'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:movie_pk>/<int:review_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/<int:review_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/<int:review_pk>/hate/', views.hate, name='hate'),
    path('<int:movie_pk>/<int:review_pk>', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/<int:review_pk>/create/', views.comment_create, name='comment_create'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

final_pjt/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FINAL_PROJECT</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/58bd5ab4e8.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body class="pt-5">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <a class="navbar-brand" href="{% url 'movies:index' %}"><img src="https://fontmeme.com/permalink/200614/7ea66ee7516d87b1b4501c5e8a10a24d.png" alt="SSAFLIX"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies:index' %}">SSAFLIX</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class='nav-link' href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          <li class='nav-item'>
            <p class='text-white p-2 m-0'>WELCOME, {{ request.user.username }}</p>
          </li>
        {% else %}
          <li class="nav-item">
            <a class='nav-link' href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class='nav-link' href="{% url 'accounts:signup' %}">Signup</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="pt-5">
    {% block content %}
    {% endblock %}
  </div>
    
  <!-- <footer>
    <p>김선민, 김현준 조 final project</p>
    <p><a href="https://github.com/tyhtm3/final_pjt">Github Source</a></p>
  </footer> -->

  <style>
    body {
      /* height: 100vh; */
    }
    div {
        background-color: #141414;
        /* height: 100%; */
    }
    .navbar{
        background-color: #141414;
    }
  </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>