final_pjt/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

final_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rank_save/', views.rank_save, name='rank_save'),
    path('<int:movie_pk>/rank_delete/', views.rank_delete, name='rank_delete'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:movie_pk>/<int:review_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/<int:review_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/<int:review_pk>/hate/', views.hate, name='hate'),
    path('<int:movie_pk>/<int:review_pk>', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/<int:review_pk>/create/', views.comment_create, name='comment_create'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

final_pjt/movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=100)
    backdrop_path = models.CharField(max_length=100)
    genres = models.ManyToManyField(Genre, related_name='genre_movie')

class Rank(models.Model):
    num = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    hate_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='hate_articles')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

final_pjt/movies/forms.py
from django import forms
from .models import Review, Comment, Rank

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

final_pjt/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator

from .models import Movie, Genre, Review, Comment, Rank
from .forms import ReviewForm, CommentForm

import random
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    #Random
    moviesRandom = random.sample(list(movies),18)
    movies_1=moviesRandom[:6]
    movies_2=moviesRandom[6:12]
    movies_3=moviesRandom[12:]

    # 1. 사용자가 7점이상 평점을 준 영화 중 가장 많은 장르의 영화를 추천
    # 사용자가 로그인하고 평점을 준 영화가 있을 경우 (이미 평점을 준 영화 제외)
    # 목록이 12개가 안되면 모든 장르 영화 중 인기도순으로 채워넣는다.
    highrank_genre = []
    if request.user.is_authenticated and Rank.objects.all().filter(user=request.user, num__gte=7).exists():
        ranks = Rank.objects.all().filter(user=request.user, num__gte=7)
        genres_dic = {}
        for rank in ranks:
            movie = rank.movie
            for genre in movie.genres.all():
                if genre.name in genres_dic:
                    genres_dic[genre.id] += 1
                else:
                    genres_dic[genre.id] = 1
        genres_sort = sorted(genres_dic.items(), key=lambda x:x[1], reverse=True)
        most_liked_genre = genres_sort[0][0]
        # 그 장르 중 인지도가 높은 순으로
        for movie in Movie.objects.order_by('-popularity'):
            if not Rank.objects.all().filter(user=request.user, movie=movie).exists():
                for genre in movie.genres.all():
                    if most_liked_genre == genre.id:
                        highrank_genre.append(movie)
                        if len(highrank_genre)==12:
                            break
                if len(highrank_genre)==12:
                    break
    if len(highrank_genre)<12:
        for movie in Movie.objects.order_by('-popularity'):
            highrank_genre.append(movie)
            if len(highrank_genre)==12:
                break

    highrank_genre_front = highrank_genre[:6]
    highrank_genre_end = highrank_genre[6:12]

    # 2. 최근 사용자가 평점을 준 영화들
    # 최근 평점을 준 순서대로 추출
    # index.html에 '사용자가 로그인을 했으면'이라는 조건 필요
    recent_movies = []
    if request.user.is_authenticated and Rank.objects.all().filter(user=request.user).exists():
        ranks = Rank.objects.all().filter(user=request.user).order_by('-pk')
        for rank in ranks:
            movie = rank.movie
            recent_movies.append(movie)
            if len(recent_movies)==12:
                break
    if recent_movies:
        recent_movies_front = recent_movies[:6]
        if len(recent_movies)>6:
            recent_movies_end = recent_movies[6:]
        else:
            recent_movies_end = []
    else:
        recent_movies_front = []
        recent_movies_end = []

    # 3. 높은 평점을 가진 영화 순서대로(기존 json 파일에 있는 평균평점이용)
    # 기존 Movie 모델에 있는 속성으로만 바꿔주면 그에 맞는 알고리즘이 된다.
    highvote_movies = Movie.objects.order_by('-vote_average')[:12]
    highvote_movies_front = highvote_movies[:6]
    highvote_movies_end = highvote_movies[6:]
    logomovie = random.sample(highrank_genre,1)[0]
  
    context = {
        'highrank_genre_front' : highrank_genre_front,
        'highrank_genre_end' : highrank_genre_end,
        'recent_movies_front' : recent_movies_front,
        'recent_movies_end' : recent_movies_end,
        'highvote_movies_front' : highvote_movies_front,
        'highvote_movies_end' : highvote_movies_end,
        'movies_1':movies_1,
        'movies_2': movies_2,
        'movies_3': movies_3,
        'logomovie': logomovie,
    }
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    rank_num = 0
    if request.user.is_authenticated:
        if Rank.objects.all().filter(movie=movie, user=request.user).exists():
            rank = get_object_or_404(Rank, movie=movie, user=request.user)
            rank_num = rank.num
    ranks = Rank.objects.all().filter(movie=movie)
    sum_ranks = 0
    cnt_ranks = 0
    for rank in ranks:
        sum_ranks += rank.num
        cnt_ranks += 1
    if cnt_ranks:
        avg_rank = round(sum_ranks/cnt_ranks, 1)
    else:
        avg_rank = 0
    reviews = movie.review_set.all().order_by('-pk')
    paginator = Paginator(reviews, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'avg_rank' : avg_rank,
        'movie' : movie,
        'page_obj' : page_obj,
        'rank_num' : [1]*rank_num+[0]*(10-rank_num)
    }
    return render(request, 'movies/detail.html', context)

@login_required
def create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.movie = movie
            review.save()
            return redirect('movies:review_detail', movie.pk, review.pk)
    else:
        form = ReviewForm()
    context = {
        'form' : form,
        'movie' : movie,
    }
    return render(request, 'movies/form.html', context)

@login_required
@require_POST
def rank_save(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    user = request.user
    if Rank.objects.all().filter(movie=movie, user=user).exists():
        rank = get_object_or_404(Rank, movie=movie, user=user)
    else:
        rank = Rank(movie=movie, user=user)
    num = request.POST.get('num', None)
    rank.num = num
    rank.save()
    return JsonResponse({})

@login_required
@require_POST
def rank_delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    user = request.user
    if Rank.objects.all().filter(movie=movie, user=user).exists():
        rank = get_object_or_404(Rank, movie=movie, user=user)
        rank.delete()
    return JsonResponse({})

@login_required
def update(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user==review.user:
        if request.method=='POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.movie = movie
                review.save()
                return redirect('movies:review_detail', movie.pk, review.pk)
        else:
            form = ReviewForm(instance=review)
        context = {
            'review' : review,
            'movie' : movie,
            'form' : form
        }
        return render(request, 'movies/form.html', context)
    else:
        return redirect('movies:review_detail', movie.pk, review.pk)

@login_required
def delete(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user==review.user:
        review.delete()
    else:
        return redirect('movies:review_detail', movie.pk, review.pk)
    return redirect('movies:detail', movie.pk)

@login_required
def like(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    if review.like_users.filter(id=request.user.pk).exists():
        review.like_users.remove(request.user)
        liked = False
        hated = False
    elif review.hate_users.filter(id=request.user.pk).exists():
        review.hate_users.remove(request.user)
        review.like_users.add(request.user)
        liked = True
        hated = True
    else:
        review.like_users.add(request.user)
        liked = True
        hated = False
    return JsonResponse({
        'liked' : liked,
        'hated' : hated,
        'like_count' : review.like_users.count(),
        'hate_count' : review.hate_users.count(),
    })

@login_required
def hate(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    if review.hate_users.filter(id=request.user.pk).exists():
        review.hate_users.remove(request.user)
        liked = False
        hated = False
    elif review.like_users.filter(id=request.user.pk).exists():
        review.like_users.remove(request.user)
        review.hate_users.add(request.user)
        liked = True
        hated = True
    else:
        review.hate_users.add(request.user)
        liked = False
        hated = True
    return JsonResponse({
        'liked' : liked,
        'hated' : hated,
        'like_count' : review.like_users.count(),
        'hate_count' : review.hate_users.count(),
    })

def review_detail(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    form = CommentForm()
    context = {
        'movie' : movie,
        'review' : review,
        'form' : form,
    }
    return render(request, 'movies/review_detail.html', context)

@login_required
@require_POST
def comment_create(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.save()
    return redirect('movies:review_detail', movie.pk, review.pk)

@login_required
def comment_update(request, movie_pk, review_pk, comment_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method=='POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)

final_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load bootstrap4 %}

{% block content %}
  <div class="container-fluid mb-3" style="background-color: #141414;">
    <div class="row" style="height: 700px;">
      <div id="movie-info" class="col-0 col-sm-4 my-auto">
        <div class="text-right" style="color:yellow; font-size: larger;">
          {% if avg_rank == 0 %}
            <p>등록된 별점이 없습니다.</p>
          {% else %}
            <p>평균별점: {{ avg_rank }}</p>
          {% endif %}
        </div>
        <p id="movie-title" class="text-white">{{ movie.title }}</p>
        <p id="movie-overview" class="text-white">{{ movie.overview }}</p>
      </div>
      <div id="backdrop_img" class="col-0 col-sm-8"></div>
      <!-- <div class="col-12 col-sm-0" style="height: 500px;"><img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt=""></div> -->
    </div>
  </div>

  <div class="container text-center my-5 align-middle text-white">
    <h2>나의 별점은?</h2>
    <div class="starRev">
      {% for i in rank_num %}
        {% if i %}
          <span class="starR on">별</span>
        {% else %}
          <span class="starR">별</span>
        {% endif %}
      {% endfor %}
      <button class="btn btn-secondary rank-save">저장</button>
      <button class="btn btn-secondary rank-delete">삭제</button>
    </div>
  </div>

  <div class="container text-white text-center p-3 mb-2 bg my-3" style="background-color: #141414;">
    <h2 class="my-3">REVIEW</h2>
      <div class="text-right my-2">
       <button type="button" class="btn btn-secondary"><a href="{% url 'movies:create' movie.pk %}" class="text-decoration-none text-white">후기 남기러 가기</a></button>
      </div>
      <table class="table table-dark">
          <thead>
              <tr>
                  <th scope="col">#</th>
                  <th scope="col">제목</th>
                  <th scope="col">작성자</th>
                  <th scope="col">좋아요</th>
              </tr>
          </thead>
          <tbody class="justify-content-center">
              {% for review in page_obj %}
              <tr>
                  <th scope="row">{{ review.pk }}</th>
                  <td><a href="{% url 'movies:review_detail' movie.pk review.pk %}" class="text-decoration-none text-white">{{ review.title }}</a></td>
                  <td>{{ review.user }}</td>
                  <td>{{ review.like_users.all|length }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% bootstrap_paginate page_obj range=5 show_prev_next="false" show_first_last="true" extra_pagination_classes="justify-content-center" %}
  </div>
</div>

<style>
  #backdrop_img {
    background: linear-gradient(to left, transparent, #141414),
                url("https://image.tmdb.org/t/p/original/{{ movie.backdrop_path }}");
    background-size: 100% 100%;
    background-repeat: no-repeat;
  }
  #movie-info {
  font-family: 'Do Hyeon', sans-serif;
  }
  #movie-title {
    font-size: 3.5em;
  }
  #movie-overview {
    font-size: large;
  }
  .starR{
    background: url('http://miuu227.godohosting.com/images/icon/ico_review.png') no-repeat right 0;
    background-size: auto 100%;
    width: 30px;
    height: 30px;
    display: inline-block;
    text-indent: -9999px;
    cursor: pointer;
  }
  .starR.on{
    background-position:0 0;
  }
</style>

<script>
  var num = 0
  $('.starRev span').click(function(){
    $(this).parent().children('span').removeClass('on');
    $(this).addClass('on').prevAll('span').addClass('on');
    num = $('.on').length;
    console.log(num)
    return false;
  });

  $('.rank-save').click(function() {
    $.ajax({
      type:'POST',
      url: "{% url 'movies:rank_save' movie.pk %}",
      data: {
        'num': num,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
      dataType: "json",
      success: function(response) {
        console.log('성공');
        alert('별점이 저장되었습니다.')
      },
      error: function(error) {
        console.log('실패')
        console.log(error)
        alert('로그인 해주세요')
      }
    })
  })
  $('.rank-delete').click(function() {
    $.ajax({
      type:'POST',
      url: "{% url 'movies:rank_delete' movie.pk %}",
      data: {
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
      dataType: "json",
      success: function(response) {
        console.log('성공');
        alert('별점이 삭제되었습니다.')
      },
      error: function(error) {
        console.log('실패')
        console.log(error)
        alert('로그인 해주세요')
      }
    })
  })
</script>
{% endblock %}

final_pjt/movies/templates/movies/form.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

<div class="container text-white">
    {% if request.resolver_match.url_name == 'create' %}
        <h2>게시글 작성</h2>
    {% elif request.resolver_match.url_name == 'update' %}
        <h2>게시글 수정</h2>
    {% elif request.resolver_match.url_name == 'comment_create' %}
        <h2>댓글 작성</h2>
    {% elif request.resolver_match.url_name == 'comment_update' %}
        <h2>댓글 수정</h2>
    {% endif %}

    <span class="custom-br"></span>

    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-secondary float-right mx-3">완료</button>
    </form>

    {% if request.resolver_match.url_name == 'create' %}
        <a class="btn btn-secondary float-right" href="{% url 'movies:detail' movie.pk %}" role="button">뒤로가기</a>
    {% else %}
        <a class="btn btn-secondary float-right" href="{% url 'movies:review_detail' movie.pk review.pk %}" role="button">뒤로가기</a>
    {% endif %}
    <div style="background-color: #141414; height:500px;"></div>
</div>

<style>
    .custom-br {
      display:block;
      width: 100%;
      height: 3px;
      background-color: white; /*change color*/
      margin-top: 10px;
      margin-bottom: 10px;
    }
    </style>

{% endblock %}

final_pjt/movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load bootstrap4 %}

{% block content %}
<div class="container text-white">
    <div class="text-center">
        <h1 class="py-3">게시글 상세보기</h1>
    </div>
    
    <span class="custom-br"></span>

    <div class="row">
        <div class="col-9">
            <p>제목 : {{ review.title }}</p>
            <p>작성자 : {{ review.user }}</p>
            내용 :<p>{{ review.content }}</p>
            {% if request.user in review.like_users.all %}
                <button class="like-button btn btn-success">
                    좋아요 <span id="like-count-{{ movie.pk }}" class="badge badge-light">{{ review.like_users.all|length }}</span>
                    <span class="sr-only">unread messages</span></button>
            {% else %}
                <button class="like-button btn btn-secondary">
                    좋아요 <span id="like-count-{{ movie.pk }}" class="badge badge-light">{{ review.like_users.all|length }}</span>
                    <span class="sr-only">unread messages</span></button>
            {% endif %}

            {% if request.user in review.hate_users.all %}
                <button class="hate-button btn btn-danger">
                    싫어요 <span id="hate-count-{{ movie.pk }}" class="badge badge-light">{{ review.hate_users.all|length }}</span>
                    <span class="sr-only">unread messages</span></button>
            {% else %}
                <button class="hate-button btn btn-secondary">
                    싫어요 <span id="hate-count-{{ movie.pk }}" class="badge badge-light">{{ review.hate_users.all|length }}</span>
                    <span class="sr-only">unread messages</span></button>
            {% endif %}
            
            {% for rankk in review.user.rank_set.all %}
                {% if rankk.movie == movie %}
                    <p class="text-right">평점: <span style="color: yellow;">★</span> x {{ rankk.num }}</p>
                {% endif %}
            {% endfor %}
            <p class="text-right">생성: {{ review.created_at }}</p>
            <p class="text-right">수정: {{ review.updated_at }}</p>
        </div>
        <div class="col-3">
            <img class="img-fluid" src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="movie-poster">
        </div>
    </div>

    <!-- <span class="custom-br"></span> -->

    <a  class="btn btn-secondary float-right mx-3" href="{% url 'movies:detail' movie.pk %}" role="button">뒤로가기</a>
    <a  class="btn btn-secondary float-left mx-3" href="{% url 'movies:update' movie.pk review.pk %}" role="button">수정</a>
    <form action="{% url 'movies:delete' movie.pk review.pk %}" method="POST">
        {% csrf_token %}
        <button  class="btn btn-secondary" type="submit">삭제</button>
    </form>
    
    <span class="custom-br"></span>

    <h5 class="my-3">댓글목록 ({{ review.comment_set.all|length }}개의 댓글이 있습니다.)</h5>
    {% for comment in review.comment_set.all %}
        <div>
            <p>작성자: {{ comment.user }}</p>
            <p>내용: {{ comment.content }}</p>
            {% if request.user == comment.user %}
                <div class="text-right">
                    <div class="d-inline-block">
                        <a class="btn btn-secondary" href="{% url 'movies:comment_update' movie.pk review.pk comment.pk %}" role="button">수정</a>
                    </div>
                    <form class="d-inline-block" action="{% url 'movies:comment_delete' movie.pk review.pk comment.pk %}" method="POST">
                        {% csrf_token %}
                        <div class="text-right d-inline-block">
                            <button class="btn btn-secondary mx-3" type="submit">삭제</button>
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
        <span class="custom-br"></span>
    {% empty %}
        <p>첫번째 댓글의 주인공이 되세요.</p>
    {% endfor %}
    
    {% if user.is_authenticated %}
    <form action="{% url 'movies:comment_create' movie.pk review.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-success float-right mx-3">댓글작성</button>
    </form>
    {% else %}
    <p>댓글은 로그인이 필요합니다.</p><hr>
    {% endif %}
    <div style="background-color: #141414; height:100px;"></div>
</div>

<script>
    movieId = {{ movie.pk }}
    reviewId = {{ review.pk }}
    const likeButtons = document.querySelectorAll('.like-button')
    const hateButtons = document.querySelectorAll('.hate-button')
    likeButtons.forEach(function(likeButton) {
        likeButton.addEventListener('click', function() {
            {% if request.user.is_authenticated %}
            axios.get(`/movies/${movieId}/${reviewId}/like/`)
                .then(response =>{
                    if (response.data.liked && response.data.hated) {
                        $(this).addClass('btn-success');
                        hateButtons.forEach(function(hateButton) {
                            $(hateButton).removeClass('btn-danger')
                            $(hateButton).addClass('btn-secondary')
                        })
                    } else if (response.data.liked) {
                        $(this).addClass('btn-success')
                    } else {
                        $(this).removeClass('btn-success')
                        $(this).addClass('btn-secondary')
                    }
                    document.querySelector(`#like-count-${movieId}`).innerText = response.data.like_count
                    document.querySelector(`#hate-count-${movieId}`).innerText = response.data.hate_count
                })
                .catch(error => {
                    console.log(error)
                })
            {% else %}
                alert('로그인이 필요합니다.')
            {% endif %}
        })
    })
    hateButtons.forEach(function(hateButton) {
        hateButton.addEventListener('click', function() {
            {% if request.user.is_authenticated %}
            axios.get(`/movies/${movieId}/${reviewId}/hate/`)
                .then(response =>{
                    if (response.data.liked && response.data.hated) {
                        $(this).addClass('btn-danger');
                        likeButtons.forEach(function(likeButton) {
                            $(likeButton).removeClass('btn-success')
                            $(likeButton).addClass('btn-secondary')
                        })
                    } else if (response.data.hated) {
                        $(this).addClass('btn-danger')
                    } else {
                        $(this).removeClass('btn-danger')
                        $(this).addClass('btn-secondary')
                    }
                    document.querySelector(`#like-count-${movieId}`).innerText = response.data.like_count
                    document.querySelector(`#hate-count-${movieId}`).innerText = response.data.hate_count
                })
                .catch(error => {
                    console.log(error)
                })
            {% else %}
                alert('로그인이 필요합니다.')
            {% endif %}
        })
    })
</script>

<style>
.custom-br {
  display:block;
  width: 100%;
  height: 3px;
  background-color: white; /*change color*/
  margin-top: 10px;
  margin-bottom: 10px;
}
</style>
{% endblock %}